<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1"><dataset_header DisableRI="yes" DatasetObj="1004928896.09" DateFormat="mdy" FullHeader="no" SCMManaged="yes" YearOffset="1950" DatasetCode="RYCSO" NumericFormat="AMERICAN" NumericDecimal="." OriginatingSite="91" NumericSeparator=","/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" version_date="08/04/2004" version_time="58883" version_user="admin" deletion_flag="no" entity_mnemonic="RYCSO" key_field_value="912.7692" record_version_obj="913.7692" version_number_seq="17" secondary_key_value="PaletteSmartPanel#CHR(1)#0" import_version_number_seq="17"><smartobject_obj>912.7692</smartobject_obj>
<object_filename>PaletteSmartPanel</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>503.7692</object_type_obj>
<product_module_obj>13899.81</product_module_obj>
<layout_obj>1003516362</layout_obj>
<object_description>Palette SmartPanel</object_description>
<object_path>ry/tem</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>no</runnable_from_menu>
<container_object>yes</container_object>
<disabled>no</disabled>
<run_persistent>no</run_persistent>
<run_when></run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>0</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>912.7692</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>14085.81</object_instance_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14067.81</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>CommitPanel</instance_name>
<instance_description>Commit Panel</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>14080.81</object_instance_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14069.81</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>NavigationPanel-Icons</instance_name>
<instance_description>NavigationPanel-Icons</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>14075.81</object_instance_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14071.81</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>NavigationPanel-Labels</instance_name>
<instance_description>NavigationPanel-Labels</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1975.7692</object_instance_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>SmartPanel Default Choose</instance_name>
<instance_description>SmartPanel Default Choose</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>14090.81</object_instance_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14073.81</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>UpdatePanel(Standard)</instance_name>
<instance_description>UpdatePanel Standard</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1976.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteDirectoryList</attribute_label>
<character_value>adm2,.,ry/tem</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1977.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteFilter</attribute_label>
<character_value>p*.r,p*.w,p*.*,*.*</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1978.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteImageDown</attribute_label>
<character_value>adeicon/wp_down 0,168</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1979.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteImageUp</attribute_label>
<character_value>adeicon/wp_up 0,168</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1980.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteIsDefault</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1981.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteLabel</attribute_label>
<character_value>Smart&amp;Panel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14076.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14071.81</smartobject_obj>
<object_instance_obj>14075.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteLabel</attribute_label>
<character_value>Navigation Panel (&amp;Labels)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14081.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14069.81</smartobject_obj>
<object_instance_obj>14080.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteLabel</attribute_label>
<character_value>Navigation Panel (&amp;Icons)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14086.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14067.81</smartobject_obj>
<object_instance_obj>14085.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteLabel</attribute_label>
<character_value>C&amp;ommit Panel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14091.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14073.81</smartobject_obj>
<object_instance_obj>14090.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteLabel</attribute_label>
<character_value>Update Panel (&amp;Standard)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1982.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteOrder</attribute_label>
<character_value></character_value>
<integer_value>7</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14078.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14071.81</smartobject_obj>
<object_instance_obj>14075.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteOrder</attribute_label>
<character_value></character_value>
<integer_value>10</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14083.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14069.81</smartobject_obj>
<object_instance_obj>14080.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteOrder</attribute_label>
<character_value></character_value>
<integer_value>5</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14088.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14067.81</smartobject_obj>
<object_instance_obj>14085.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteOrder</attribute_label>
<character_value></character_value>
<integer_value>20</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14093.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14073.81</smartobject_obj>
<object_instance_obj>14090.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteOrder</attribute_label>
<character_value></character_value>
<integer_value>15</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>4515.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14067.81</smartobject_obj>
<object_instance_obj>14085.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteRenderer</attribute_label>
<character_value>adm2/pcommit.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>4516.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14069.81</smartobject_obj>
<object_instance_obj>14080.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteRenderer</attribute_label>
<character_value>adm2/pnavico.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>4517.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14071.81</smartobject_obj>
<object_instance_obj>14075.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteRenderer</attribute_label>
<character_value>adm2/pnavlbl.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>4518.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14073.81</smartobject_obj>
<object_instance_obj>14090.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteRenderer</attribute_label>
<character_value>adm2/pupdsav.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1983.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteTitle</attribute_label>
<character_value>Choose SmartPanel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1984.7692</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>1555.7692</smartobject_obj>
<object_instance_obj>1975.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteType</attribute_label>
<character_value>SmartPanel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14079.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14071.81</smartobject_obj>
<object_instance_obj>14075.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteType</attribute_label>
<character_value>SmartPanel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14084.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14069.81</smartobject_obj>
<object_instance_obj>14080.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteType</attribute_label>
<character_value>SmartPanel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14089.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14067.81</smartobject_obj>
<object_instance_obj>14085.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteType</attribute_label>
<character_value>SmartPanel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14094.81</attribute_value_obj>
<object_type_obj>243158</object_type_obj>
<container_smartobject_obj>912.7692</container_smartobject_obj>
<smartobject_obj>14073.81</smartobject_obj>
<object_instance_obj>14090.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PaletteType</attribute_label>
<character_value>SmartPanel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>912.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>