<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1" deletion_flag="no" entity_mnemonic="GSTDF" import_version_number_seq="1.49" key_field_value="10310.49" record_version_obj="10311.49" secondary_key_value="" version_date="10/03/2007" version_number_seq="2.49" version_time="59447" version_user="admin"><dataset_header DatasetCode="RYCSO" DatasetObj="1004928896.09" DateFormat="mdy" DisableRI="yes" FullHeader="no" NumericDecimal="." NumericFormat="AMERICAN" NumericSeparator="," OriginatingSite="94" SCMManaged="yes" YearOffset="1950"/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" deletion_flag="no" entity_mnemonic="RYCSO" import_version_number_seq="11" key_field_value="530.7692" record_version_obj="531.7692" secondary_key_value="templateContainer#CHR(1)#0" version_date="10/03/2007" version_number_seq="8.49" version_time="59057" version_user="admin"><smartobject_obj>530.7692</smartobject_obj>
<object_filename>templateContainer</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>501.7692</object_type_obj>
<product_module_obj>13899.81</product_module_obj>
<layout_obj>1003516362</layout_obj>
<object_description>Template for Containers</object_description>
<object_path>ry/tem</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>yes</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>no</runnable_from_menu>
<container_object>no</container_object>
<disabled>no</disabled>
<run_persistent>no</run_persistent>
<run_when></run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>0</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>530.7692</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1647.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Dependent Window</instance_name>
<instance_description>Dependent Window</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>2106.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1601.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Dialog</instance_name>
<instance_description>Dialog</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>13989.81</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13987.81</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>DialogTTY</instance_name>
<instance_description>Dialog TTY</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1687.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Dynamic SmartBusinessObject</instance_name>
<instance_description>Dynamic SmartBusinessObject</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1695.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Dynamic SmartFrame</instance_name>
<instance_description>Dynamic SmartFrame</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1671.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Dynamic Treeview(1)</instance_name>
<instance_description>Dynamic Treeview</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1679.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Independent Window</instance_name>
<instance_description>Independent Window</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1663.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Menu Controller</instance_name>
<instance_description>Menu Controller</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>2976.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1057.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Static Simple Container</instance_name>
<instance_description>Static Simple Container</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1713.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1545.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Static SmartDialog</instance_name>
<instance_description>Static SmartDialog</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1703.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1549.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Static SmartFrame</instance_name>
<instance_description>Static SmartFrame</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1708.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1543.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>Static SmartWindow</instance_name>
<instance_description>Static SmartWindow</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>2096.7692</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1599.7692</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>Window</instance_name>
<instance_description>Window</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>13996.81</object_instance_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13994.81</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>WindowTTY</instance_name>
<instance_description>Window TTY</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1648.7692</attribute_value_obj>
<object_type_obj>1003498200</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<object_instance_obj>1647.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DynamicObject</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1664.7692</attribute_value_obj>
<object_type_obj>1003554179</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<object_instance_obj>1663.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DynamicObject</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1672.7692</attribute_value_obj>
<object_type_obj>1005097659.101</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<object_instance_obj>1671.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DynamicObject</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1680.7692</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<object_instance_obj>1679.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DynamicObject</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1688.7692</attribute_value_obj>
<object_type_obj>25139.7063</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<object_instance_obj>1687.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DynamicObject</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1696.7692</attribute_value_obj>
<object_type_obj>32212.48</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<object_instance_obj>1695.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DynamicObject</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1649.7692</attribute_value_obj>
<object_type_obj>1003498200</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<object_instance_obj>1647.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>src/adm2/template/dynfold.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1665.7692</attribute_value_obj>
<object_type_obj>1003554179</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<object_instance_obj>1663.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>src/adm2/template/dynmenc.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1673.7692</attribute_value_obj>
<object_type_obj>1005097659.101</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<object_instance_obj>1671.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>src/adm2/template/dyntvcontnr.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1681.7692</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<object_instance_obj>1679.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>src/adm2/template/dynobjc.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1689.7692</attribute_value_obj>
<object_type_obj>25139.7063</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<object_instance_obj>1687.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rydynsbowiz.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1697.7692</attribute_value_obj>
<object_type_obj>32212.48</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<object_instance_obj>1695.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/dynframewiz.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1704.7692</attribute_value_obj>
<object_type_obj>243157</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1549.7692</smartobject_obj>
<object_instance_obj>1703.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rytemsmartframe.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1709.7692</attribute_value_obj>
<object_type_obj>491</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1543.7692</smartobject_obj>
<object_instance_obj>1708.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rytemsmartwindow.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1714.7692</attribute_value_obj>
<object_type_obj>489</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1545.7692</smartobject_obj>
<object_instance_obj>1713.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rytemsmartdialog.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2097.7692</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1599.7692</smartobject_obj>
<object_instance_obj>2096.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rytemwindow.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2107.7692</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1601.7692</smartobject_obj>
<object_instance_obj>2106.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rytemstaticdialog.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2977.7692</attribute_value_obj>
<object_type_obj>200000003061.66</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1057.7692</smartobject_obj>
<object_instance_obj>2976.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>src/adm2/template/cntnrsimpl.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>13990.81</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13987.81</smartobject_obj>
<object_instance_obj>13989.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rytemstaticttydialog.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>13997.81</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13994.81</smartobject_obj>
<object_instance_obj>13996.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateFile</attribute_label>
<character_value>ry/tem/rytemttywindow.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1650.7692</attribute_value_obj>
<object_type_obj>1003498200</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<object_instance_obj>1647.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1666.7692</attribute_value_obj>
<object_type_obj>1003554179</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<object_instance_obj>1663.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1678.7692</attribute_value_obj>
<object_type_obj>1005097659.101</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<object_instance_obj>1671.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1682.7692</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<object_instance_obj>1679.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1690.7692</attribute_value_obj>
<object_type_obj>25139.7063</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<object_instance_obj>1687.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1698.7692</attribute_value_obj>
<object_type_obj>32212.48</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<object_instance_obj>1695.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1705.7692</attribute_value_obj>
<object_type_obj>243157</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1549.7692</smartobject_obj>
<object_instance_obj>1703.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1710.7692</attribute_value_obj>
<object_type_obj>491</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1543.7692</smartobject_obj>
<object_instance_obj>1708.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1715.7692</attribute_value_obj>
<object_type_obj>489</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1545.7692</smartobject_obj>
<object_instance_obj>1713.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2098.7692</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1599.7692</smartobject_obj>
<object_instance_obj>2096.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2109.7692</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1601.7692</smartobject_obj>
<object_instance_obj>2106.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2978.7692</attribute_value_obj>
<object_type_obj>200000003061.66</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1057.7692</smartobject_obj>
<object_instance_obj>2976.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>13991.81</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13987.81</smartobject_obj>
<object_instance_obj>13989.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>13998.81</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13994.81</smartobject_obj>
<object_instance_obj>13996.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateGroup</attribute_label>
<character_value>Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1651.7692</attribute_value_obj>
<object_type_obj>1003498200</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<object_instance_obj>1647.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateImageFile</attribute_label>
<character_value>adeicon/smartWindow.bmp</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1667.7692</attribute_value_obj>
<object_type_obj>1003554179</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<object_instance_obj>1663.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateImageFile</attribute_label>
<character_value>adeicon/smartwindow.bmp</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1674.7692</attribute_value_obj>
<object_type_obj>1005097659.101</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<object_instance_obj>1671.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateImageFile</attribute_label>
<character_value>adeicon/smartwindow.bmp</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1683.7692</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<object_instance_obj>1679.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateImageFile</attribute_label>
<character_value>adeicon/smartwindow.bmp</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1691.7692</attribute_value_obj>
<object_type_obj>25139.7063</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<object_instance_obj>1687.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateImageFile</attribute_label>
<character_value>adeicon/smartwindow.bmp</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1699.7692</attribute_value_obj>
<object_type_obj>32212.48</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<object_instance_obj>1695.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateImageFile</attribute_label>
<character_value>adeicon/smartwindow.bmp</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1652.7692</attribute_value_obj>
<object_type_obj>1003498200</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<object_instance_obj>1647.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Dependent Window (DynFold)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1668.7692</attribute_value_obj>
<object_type_obj>1003554179</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<object_instance_obj>1663.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Menu Controller (DynMenc)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1675.7692</attribute_value_obj>
<object_type_obj>1005097659.101</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<object_instance_obj>1671.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Dynamic Treeview (DynTree)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1684.7692</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<object_instance_obj>1679.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Independent Window (DynObjc)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1692.7692</attribute_value_obj>
<object_type_obj>25139.7063</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<object_instance_obj>1687.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Dynamic SmartBusinessObject (DynSBO)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1700.7692</attribute_value_obj>
<object_type_obj>32212.48</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<object_instance_obj>1695.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Dynamic SmartFrame (DynFrame)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1706.7692</attribute_value_obj>
<object_type_obj>243157</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1549.7692</smartobject_obj>
<object_instance_obj>1703.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Static Smart&amp;Frame</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1711.7692</attribute_value_obj>
<object_type_obj>491</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1543.7692</smartobject_obj>
<object_instance_obj>1708.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Static SmartWindow</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1716.7692</attribute_value_obj>
<object_type_obj>489</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1545.7692</smartobject_obj>
<object_instance_obj>1713.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Static SmartDialog</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2099.7692</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1599.7692</smartobject_obj>
<object_instance_obj>2096.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>&amp;Window</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2108.7692</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1601.7692</smartobject_obj>
<object_instance_obj>2106.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Dialog</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2979.7692</attribute_value_obj>
<object_type_obj>200000003061.66</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1057.7692</smartobject_obj>
<object_instance_obj>2976.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>Static Simple Smart&amp;Container</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>13992.81</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13987.81</smartobject_obj>
<object_instance_obj>13989.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>TTY &amp;Dialog</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>13999.81</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13994.81</smartobject_obj>
<object_instance_obj>13996.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateLabel</attribute_label>
<character_value>TTY &amp;Window</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1653.7692</attribute_value_obj>
<object_type_obj>1003498200</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<object_instance_obj>1647.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>15</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1669.7692</attribute_value_obj>
<object_type_obj>1003554179</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<object_instance_obj>1663.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>10</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1676.7692</attribute_value_obj>
<object_type_obj>1005097659.101</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<object_instance_obj>1671.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>20</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1685.7692</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<object_instance_obj>1679.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>5</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1693.7692</attribute_value_obj>
<object_type_obj>25139.7063</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<object_instance_obj>1687.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>25</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1701.7692</attribute_value_obj>
<object_type_obj>32212.48</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<object_instance_obj>1695.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>30</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1707.7692</attribute_value_obj>
<object_type_obj>243157</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1549.7692</smartobject_obj>
<object_instance_obj>1703.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>45</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1712.7692</attribute_value_obj>
<object_type_obj>491</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1543.7692</smartobject_obj>
<object_instance_obj>1708.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>35</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1717.7692</attribute_value_obj>
<object_type_obj>489</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1545.7692</smartobject_obj>
<object_instance_obj>1713.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>40</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2100.7692</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1599.7692</smartobject_obj>
<object_instance_obj>2096.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>55</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2110.7692</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1601.7692</smartobject_obj>
<object_instance_obj>2106.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>60</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2980.7692</attribute_value_obj>
<object_type_obj>200000003061.66</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1057.7692</smartobject_obj>
<object_instance_obj>2976.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>50</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>13993.81</attribute_value_obj>
<object_type_obj>10386.81</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13987.81</smartobject_obj>
<object_instance_obj>13989.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>70</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>14000.81</attribute_value_obj>
<object_type_obj>492</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>13994.81</smartobject_obj>
<object_instance_obj>13996.81</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplateOrder</attribute_label>
<character_value></character_value>
<integer_value>65</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1654.7692</attribute_value_obj>
<object_type_obj>1003498200</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1535.7692</smartobject_obj>
<object_instance_obj>1647.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplatePropertySheet</attribute_label>
<character_value>adeuib/_contbldrprop.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1670.7692</attribute_value_obj>
<object_type_obj>1003554179</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1533.7692</smartobject_obj>
<object_instance_obj>1663.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplatePropertySheet</attribute_label>
<character_value>adeuib/_contbldrprop.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1677.7692</attribute_value_obj>
<object_type_obj>1005097659.101</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1537.7692</smartobject_obj>
<object_instance_obj>1671.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplatePropertySheet</attribute_label>
<character_value>adeuib/_treebldrprop.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1686.7692</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1531.7692</smartobject_obj>
<object_instance_obj>1679.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplatePropertySheet</attribute_label>
<character_value>adeuib/_contbldrprop.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1694.7692</attribute_value_obj>
<object_type_obj>25139.7063</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1539.7692</smartobject_obj>
<object_instance_obj>1687.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplatePropertySheet</attribute_label>
<character_value>adeuib/_contbldrprop.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1702.7692</attribute_value_obj>
<object_type_obj>32212.48</object_type_obj>
<container_smartobject_obj>530.7692</container_smartobject_obj>
<smartobject_obj>1541.7692</smartobject_obj>
<object_instance_obj>1695.7692</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>TemplatePropertySheet</attribute_label>
<character_value>adeuib/_contbldrprop.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>530.7692</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>