<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1" deletion_flag="no" entity_mnemonic="GSTDF" import_version_number_seq="0" key_field_value="3000001173.09" record_version_obj="100000006116.39" secondary_key_value="" version_date="10/12/2006" version_number_seq="1.39" version_time="52506" version_user="admin"><dataset_header DatasetCode="RYCSO" DatasetObj="1004928896.09" DateFormat="mdy" DisableRI="yes" FullHeader="no" NumericDecimal="." NumericFormat="AMERICAN" NumericSeparator="," OriginatingSite="93" SCMManaged="yes" YearOffset="1950"/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" deletion_flag="no" entity_mnemonic="rycso" import_version_number_seq="17.66" key_field_value="1003574037" record_version_obj="3000049965.09" secondary_key_value="rycatobjcw#CHR(1)#0" version_date="10/12/2006" version_number_seq="17.66" version_time="52444" version_user="Admin"><smartobject_obj>1003574037</smartobject_obj>
<object_filename>rycatobjcw</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>1003498202</object_type_obj>
<product_module_obj>1004874710.09</product_module_obj>
<layout_obj>1007500101.09</layout_obj>
<object_description>Attribute Control</object_description>
<object_path>ry/uib</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>yes</runnable_from_menu>
<container_object>yes</container_object>
<disabled>no</disabled>
<run_persistent>yes</run_persistent>
<run_when>ANY</run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>0</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>1003574037</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004934096</object_instance_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M91</layout_position>
<instance_name>BrowseToolbar</instance_name>
<instance_description>BrowseToolbar</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004934035</object_instance_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M11</layout_position>
<instance_name>ObjcTop</instance_name>
<instance_description>ObjcTop</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004934006</object_instance_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1004927970</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M21</layout_position>
<instance_name>rycatfiltv.w</instance_name>
<instance_description>rycatfiltv.w</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004934008</object_instance_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1003571985</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M31</layout_position>
<instance_name>rycatfullb</instance_name>
<instance_description>rycatfullb</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004933971</object_instance_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1003571922</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M11</layout_position>
<instance_name>rycatfullow</instance_name>
<instance_description>rycatfullo.w</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934163</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003578295</smartlink_type_obj>
<link_name>PrimarySdo</link_name>
<source_object_instance_obj>0</source_object_instance_obj>
<target_object_instance_obj>1004933971</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934175</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003183649</smartlink_type_obj>
<link_name>Data</link_name>
<source_object_instance_obj>1004933971</source_object_instance_obj>
<target_object_instance_obj>1004934006</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934171</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003183649</smartlink_type_obj>
<link_name>Data</link_name>
<source_object_instance_obj>1004933971</source_object_instance_obj>
<target_object_instance_obj>1004934008</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934177</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003585634</smartlink_type_obj>
<link_name>User1</link_name>
<source_object_instance_obj>1004934006</source_object_instance_obj>
<target_object_instance_obj>1004934008</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934173</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003183650</smartlink_type_obj>
<link_name>Update</link_name>
<source_object_instance_obj>1004934008</source_object_instance_obj>
<target_object_instance_obj>1004933971</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934165</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>463.5498</smartlink_type_obj>
<link_name>ContainerToolbar</link_name>
<source_object_instance_obj>1004934035</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934179</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1004934035</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934167</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1004934096</source_object_instance_obj>
<target_object_instance_obj>1004933971</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004934169</smartlink_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartlink_type_obj>1003543798</smartlink_type_obj>
<link_name>Toolbar</link_name>
<source_object_instance_obj>1004934096</source_object_instance_obj>
<target_object_instance_obj>1004934008</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004933991</attribute_value_obj>
<object_type_obj>1003183339</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1003571922</smartobject_obj>
<object_instance_obj>1004933971</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ForeignFields</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>90683.66</attribute_value_obj>
<object_type_obj>1003183339</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1003571922</smartobject_obj>
<object_instance_obj>1004933971</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PromptColumns</attribute_label>
<character_value>(ALL)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>90685.66</attribute_value_obj>
<object_type_obj>1003183339</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1003571922</smartobject_obj>
<object_instance_obj>1004933971</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>RebuildOnRepos</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>90684.66</attribute_value_obj>
<object_type_obj>1003183339</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1003571922</smartobject_obj>
<object_instance_obj>1004933971</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>RowsToBatch</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004934067</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1004934035</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Navigation-source,Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004934128</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004934096</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004934137</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004934096</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarAutoSize</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004934079</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1004934035</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>Adm2Navigation,txtaction,AstraHelp,AstraWindow,AstraAbout,AstraMenuExit,DynamicMenu</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004934140</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004934096</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>browsetableio,browsesearch,browsefunction</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004934149</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1003574037</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004934096</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarParentMenu</attribute_label>
<character_value>Attribute</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004933968</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>1003574037</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WindowName</attribute_label>
<character_value>Attribute Control</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1003574037</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>