/************************************************
Copyright (c)  2013 by Progress Software Corporation. All rights reserved.
*************************************************/
/*------------------------------------------------------------------------
    File        : ISet
    Purpose     : A collection that contains no duplicate elements.
    Syntax      : 
    Description : 
    @author hdaniels
    Created     : Wed Jan 09 09:57:42 EST 2008
    Notes       : * Based on the AutoEdge|TheFactory version
  ----------------------------------------------------------------------*/
using OpenEdge.Core.Collections.ICollection.

interface OpenEdge.Core.Collections.ISet inherits ICollection:
    /* no extra members beyond ICollection */      
end interface.
