<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1"><dataset_header DisableRI="yes" DatasetObj="1004928896.09" DateFormat="mdy" FullHeader="no" SCMManaged="yes" YearOffset="1950" DatasetCode="RYCSO" NumericFormat="AMERICAN" NumericDecimal="." OriginatingSite="91" NumericSeparator=","/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" version_date="10/03/2003" version_time="48757" version_user="admin" deletion_flag="no" entity_mnemonic="RYCSO" key_field_value="125328.9875" record_version_obj="125329.9875" version_number_seq="4.09" secondary_key_value="grpcomdynv#CHR(1)#0" import_version_number_seq="4.09"><smartobject_obj>125328.9875</smartobject_obj>
<object_filename>grpcomdynv</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>1003498162</object_type_obj>
<product_module_obj>1004874683.09</product_module_obj>
<layout_obj>0</layout_obj>
<object_description>Group to Company Allocation</object_description>
<object_path>af/obj2</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>no</runnable_from_menu>
<container_object>no</container_object>
<disabled>no</disabled>
<run_persistent>no</run_persistent>
<run_when>ANY</run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>124807.9875</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>125328.9875</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>125360.9875</ui_event_obj>
<object_type_obj>5540.409</object_type_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<object_instance_obj>125354.9875</object_instance_obj>
<event_name>VALUE-CHANGED</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>appliesToAll</event_action>
<event_parameter>YES</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>125354.9875</object_instance_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>ToAll</instance_name>
<instance_description>Dynamic TOGGLE-BOX</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>3000052881.09</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>125328.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>AppBuilderTabbing</attribute_label>
<character_value>Custom</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>125358.9875</attribute_value_obj>
<object_type_obj>5540.409</object_type_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<object_instance_obj>125354.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>2.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>125355.9875</attribute_value_obj>
<object_type_obj>5540.409</object_type_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<object_instance_obj>125354.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>CONTEXT-HELP-ID</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>125356.9875</attribute_value_obj>
<object_type_obj>5540.409</object_type_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<object_instance_obj>125354.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>Applies to all login companies</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>125352.9875</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>125328.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>MinHeight</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>2.19</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>125353.9875</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>125328.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>MinWidth</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>39.8</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>125359.9875</attribute_value_obj>
<object_type_obj>5540.409</object_type_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<object_instance_obj>125354.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>1.38</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>3000050281.09</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>125328.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>SuperProcedure</attribute_label>
<character_value>af/obj2/grpcomsupr.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>3000052809.09</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>125328.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>SuperProcedureMode</attribute_label>
<character_value>STATEFUL</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>125357.9875</attribute_value_obj>
<object_type_obj>5540.409</object_type_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<object_instance_obj>125354.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>37.6</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>125360.9875</ui_event_obj>
<object_type_obj>5540.409</object_type_obj>
<container_smartobject_obj>125328.9875</container_smartobject_obj>
<smartobject_obj>6318.409</smartobject_obj>
<object_instance_obj>125354.9875</object_instance_obj>
<event_name>VALUE-CHANGED</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>appliesToAll</event_action>
<event_parameter>YES</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>125328.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>