<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1"><dataset_header DisableRI="yes" DatasetObj="1004928896.09" DateFormat="mdy" FullHeader="no" SCMManaged="yes" YearOffset="1950" DatasetCode="RYCSO" NumericFormat="AMERICAN" NumericDecimal="." OriginatingSite="91" NumericSeparator=","/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" version_date="10/03/2003" version_time="48757" version_user="admin" deletion_flag="no" entity_mnemonic="RYCSO" key_field_value="124447.9875" record_version_obj="124448.9875" version_number_seq="4.09" secondary_key_value="grpusrviwv#CHR(1)#0" import_version_number_seq="4.09"><smartobject_obj>124447.9875</smartobject_obj>
<object_filename>grpusrviwv</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>1003498162</object_type_obj>
<product_module_obj>1004874683.09</product_module_obj>
<layout_obj>0</layout_obj>
<object_description>Security Group User Allocations</object_description>
<object_path>af/obj2</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>no</runnable_from_menu>
<container_object>no</container_object>
<disabled>no</disabled>
<run_persistent>no</run_persistent>
<run_when>ANY</run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>124343.9875</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>124447.9875</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124570.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<event_name>DEFAULT-ACTION</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Available</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124571.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<event_name>DEFAULT-ACTION</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Allocated</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124573.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<event_name>VALUE-CHANGED</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Available</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124574.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<event_name>MOUSE-SELECT-CLICK</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Available</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124575.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<event_name>VALUE-CHANGED</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Allocated</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124576.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<event_name>MOUSE-SELECT-CLICK</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Allocated</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124577.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>Add</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124578.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>AddAll</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124579.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>Remove</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124580.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>RemoveAll</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124480.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>buAdd</instance_name>
<instance_description>Dynamic BUTTON</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124488.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>buAddAll</instance_name>
<instance_description>Dynamic BUTTON</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124496.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>buRemove</instance_name>
<instance_description>Dynamic BUTTON</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124504.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>buRemoveAll</instance_name>
<instance_description>Dynamic BUTTON</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124525.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>fiLabelAvail</instance_name>
<instance_description>Dynamic FILL-IN</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124512.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>fiLabelSel</instance_name>
<instance_description>Dynamic FILL-IN</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124467.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>122218.9875</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>fiLoginCompanyObj</instance_name>
<instance_description>SmartDataField of type DynCombo</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124451.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>seAvailable</instance_name>
<instance_description>Dynamic SELECTION-LIST</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>124459.9875</object_instance_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<system_owned>no</system_owned>
<layout_position></layout_position>
<instance_name>seSelected</instance_name>
<instance_description>Dynamic SELECTION-LIST</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>3000052877.09</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>124447.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>AppBuilderTabbing</attribute_label>
<character_value>Custom</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124485.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>BGCOLOR</attribute_label>
<character_value></character_value>
<integer_value>8</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124493.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>BGCOLOR</attribute_label>
<character_value></character_value>
<integer_value>8</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124501.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>BGCOLOR</attribute_label>
<character_value></character_value>
<integer_value>8</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124509.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>BGCOLOR</attribute_label>
<character_value></character_value>
<integer_value>8</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124457.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>1.6</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124465.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>48.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124472.9875</attribute_value_obj>
<object_type_obj>1005111020.101</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>122218.9875</smartobject_obj>
<object_instance_obj>124467.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>17.8</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124486.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>38.6</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124494.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>38.6</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124502.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>38.6</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124510.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>38.6</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124520.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>48.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124532.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>COLUMN</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>3.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124514.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ENABLED</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124527.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ENABLED</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124469.9875</attribute_value_obj>
<object_type_obj>1005111020.101</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>122218.9875</smartobject_obj>
<object_instance_obj>124467.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>FieldName</attribute_label>
<character_value>fiLoginCompanyObj</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124453.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>FONT</attribute_label>
<character_value></character_value>
<integer_value>3</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124461.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>FONT</attribute_label>
<character_value></character_value>
<integer_value>3</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124515.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>FORMAT</attribute_label>
<character_value>X(70)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124528.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>FORMAT</attribute_label>
<character_value>X(70)</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124454.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>HEIGHT-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>5.52</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124462.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>HEIGHT-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>5.81</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124470.9875</attribute_value_obj>
<object_type_obj>1005111020.101</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>122218.9875</smartobject_obj>
<object_instance_obj>124467.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>HEIGHT-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>1.05</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124521.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>HEIGHT-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>.62</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124533.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>HEIGHT-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>.62</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124516.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>InitialValue</attribute_label>
<character_value>Allocated Users/Groups</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124529.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>InitialValue</attribute_label>
<character_value>Available Users/Groups</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124455.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>seList</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124463.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>seList-2</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124482.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>-&gt;</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124490.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>-&gt;&gt;</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124498.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>&lt;-</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124506.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>&lt;&lt;-</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124568.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>fiLabelSel</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124569.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABEL</attribute_label>
<character_value>fiLabelAvail</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124517.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABELS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124572.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LABELS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124471.9875</attribute_value_obj>
<object_type_obj>1005111020.101</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>122218.9875</smartobject_obj>
<object_instance_obj>124467.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>LocalField</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124468.9875</attribute_value_obj>
<object_type_obj>1005111020.101</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>122218.9875</smartobject_obj>
<object_instance_obj>124467.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>MasterFile</attribute_label>
<character_value>adm2/dyncombo.w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124449.9875</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>124447.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>MinHeight</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>8.91</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124450.9875</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>124447.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>MinWidth</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>84.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124476.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>MULTIPLE</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124478.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>MULTIPLE</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124522.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PRIVATE-DATA</attribute_label>
<character_value>Allocated Users/Groups</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124534.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>PRIVATE-DATA</attribute_label>
<character_value>Available Users/Groups</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124458.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>3.19</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124466.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>3.1</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124473.9875</attribute_value_obj>
<object_type_obj>1005111020.101</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>122218.9875</smartobject_obj>
<object_instance_obj>124467.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>1</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124487.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>3.48</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124495.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>4.67</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124503.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>5.86</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124511.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>7</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124523.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>2.38</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124535.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ROW</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>2.52</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124477.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>SCROLLBAR-VERTICAL</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124479.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>SCROLLBAR-VERTICAL</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>yes</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124518.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ShowPopup</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124530.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ShowPopup</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124543.9875</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>124447.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>SizeToFit</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>no</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>3000050270.09</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>124447.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>SuperProcedure</attribute_label>
<character_value>af/obj2/grpusrsupr.p</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>3000052806.09</attribute_value_obj>
<object_type_obj>1003498162</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>124447.9875</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>SuperProcedureMode</attribute_label>
<character_value>STATEFUL</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124483.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>THREE-D</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124491.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>THREE-D</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124499.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>THREE-D</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124507.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>THREE-D</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124519.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>VisualizationType</attribute_label>
<character_value>TEXT</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124531.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>VisualizationType</attribute_label>
<character_value>TEXT</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124456.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>36</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124464.9875</attribute_value_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>36</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124484.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>9.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124492.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>9.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124500.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>9.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124508.9875</attribute_value_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>9.2</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124524.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124512.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>36</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>124536.9875</attribute_value_obj>
<object_type_obj>473.99</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15870.409</smartobject_obj>
<object_instance_obj>124525.9875</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WIDTH-CHARS</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>36</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124570.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<event_name>DEFAULT-ACTION</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Available</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124571.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<event_name>DEFAULT-ACTION</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Allocated</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124573.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<event_name>VALUE-CHANGED</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Available</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124574.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124451.9875</object_instance_obj>
<event_name>MOUSE-SELECT-CLICK</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Available</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124575.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<event_name>VALUE-CHANGED</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Allocated</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124576.9875</ui_event_obj>
<object_type_obj>13577.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>15872.409</smartobject_obj>
<object_instance_obj>124459.9875</object_instance_obj>
<event_name>MOUSE-SELECT-CLICK</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>selectionMade</event_action>
<event_parameter>Allocated</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124577.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124480.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>Add</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124578.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124488.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>AddAll</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124579.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124496.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>Remove</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_ui_event"><ui_event_obj>124580.9875</ui_event_obj>
<object_type_obj>5483.409</object_type_obj>
<container_smartobject_obj>124447.9875</container_smartobject_obj>
<smartobject_obj>6304.409</smartobject_obj>
<object_instance_obj>124504.9875</object_instance_obj>
<event_name>CHOOSE</event_name>
<constant_value>no</constant_value>
<action_type>RUN</action_type>
<action_target>SELF</action_target>
<event_action>chooseButton</event_action>
<event_parameter>RemoveAll</event_parameter>
<event_disabled>no</event_disabled>
<primary_smartobject_obj>124447.9875</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>