<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1"><dataset_header DisableRI="yes" DatasetObj="1004928896.09" DateFormat="mdy" FullHeader="no" SCMManaged="yes" YearOffset="1950" DatasetCode="RYCSO" NumericFormat="AMERICAN" NumericDecimal="." OriginatingSite="91" NumericSeparator=","/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" version_date="09/20/2003" version_time="80495" version_user="admin" deletion_flag="no" entity_mnemonic="rycso" key_field_value="1004929061.09" record_version_obj="3000040649.09" version_number_seq="6.09" secondary_key_value="gscddfullb#CHR(1)#0" import_version_number_seq="6.09"><smartobject_obj>1004929061.09</smartobject_obj>
<object_filename>gscddfullb</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>1003498159</object_type_obj>
<product_module_obj>1004874683.09</product_module_obj>
<layout_obj>0</layout_obj>
<object_description>Deploy Dataset Browser</object_description>
<object_path>af/obj2</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>no</runnable_from_menu>
<container_object>no</container_object>
<disabled>no</disabled>
<run_persistent>no</run_persistent>
<run_when>ANY</run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>1004928867.09</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>1004929061.09</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>3000047913.09</attribute_value_obj>
<object_type_obj>1003498159</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>1004929061.09</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>BrowseColumnWidths</attribute_label>
<character_value>13#CHR(5)#120#CHR(5)#9#CHR(5)#17#CHR(5)#15#CHR(5)#70#CHR(5)#70</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004929061.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>7465.38</attribute_value_obj>
<object_type_obj>1003498159</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>1004929061.09</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DisplayedFields</attribute_label>
<character_value>dataset_code,dataset_description,disable_ri,source_code_data,deploy_full_data,xml_generation_procedure,default_ado_filename</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004929061.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>7467.38</attribute_value_obj>
<object_type_obj>1003498159</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>1004929061.09</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>FolderWindowToLaunch</attribute_label>
<character_value>gscddobjcw</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004929061.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>