<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1"><dataset_header DisableRI="yes" DatasetObj="1004928896.09" DateFormat="mdy" FullHeader="no" SCMManaged="yes" YearOffset="1950" DatasetCode="RYCSO" NumericFormat="AMERICAN" NumericDecimal="." OriginatingSite="91" NumericSeparator=","/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" version_date="02/09/2004" version_time="47996" version_user="admin" deletion_flag="no" entity_mnemonic="RYCSO" key_field_value="1004837652.09" record_version_obj="14148.0766" version_number_seq="6.09" secondary_key_value="gsmheobjcw#CHR(1)#0" import_version_number_seq="6.09"><smartobject_obj>1004837652.09</smartobject_obj>
<object_filename>gsmheobjcw</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>1003498202</object_type_obj>
<product_module_obj>1004874683.09</product_module_obj>
<layout_obj>1007500101.09</layout_obj>
<object_description>Help Control</object_description>
<object_path>af/obj2</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>yes</runnable_from_menu>
<container_object>yes</container_object>
<disabled>no</disabled>
<run_persistent>yes</run_persistent>
<run_when>ANY</run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>0</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>1004837652.09</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004840283.09</object_instance_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M91</layout_position>
<instance_name>BrowseToolbar</instance_name>
<instance_description>BrowseToolbar</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004840203.09</object_instance_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1004837369.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M21</layout_position>
<instance_name>gsmhefullb</instance_name>
<instance_description>gsmhefullb</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004840201.09</object_instance_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1004835127.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M11</layout_position>
<instance_name>gsmhefullo.w</instance_name>
<instance_description>gsmhefullo.w</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004840222.09</object_instance_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>M11</layout_position>
<instance_name>ObjcTop</instance_name>
<instance_description>ObjcTop</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004840350.09</smartlink_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartlink_type_obj>1003578295</smartlink_type_obj>
<link_name>PrimarySdo</link_name>
<source_object_instance_obj>0</source_object_instance_obj>
<target_object_instance_obj>1004840201.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004840358.09</smartlink_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartlink_type_obj>1003183649</smartlink_type_obj>
<link_name>Data</link_name>
<source_object_instance_obj>1004840201.09</source_object_instance_obj>
<target_object_instance_obj>1004840203.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004840360.09</smartlink_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartlink_type_obj>1003183650</smartlink_type_obj>
<link_name>Update</link_name>
<source_object_instance_obj>1004840203.09</source_object_instance_obj>
<target_object_instance_obj>1004840201.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004840352.09</smartlink_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartlink_type_obj>463.5498</smartlink_type_obj>
<link_name>ContainerToolbar</link_name>
<source_object_instance_obj>1004840222.09</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004840362.09</smartlink_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1004840222.09</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004840354.09</smartlink_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1004840283.09</source_object_instance_obj>
<target_object_instance_obj>1004840201.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004840356.09</smartlink_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartlink_type_obj>1003543798</smartlink_type_obj>
<link_name>Toolbar</link_name>
<source_object_instance_obj>1004840283.09</source_object_instance_obj>
<target_object_instance_obj>1004840203.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840211.09</attribute_value_obj>
<object_type_obj>1003498159</object_type_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1004837369.09</smartobject_obj>
<object_instance_obj>1004840203.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>FolderWindowToLaunch</attribute_label>
<character_value>gsmhefol2w</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840254.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1004840222.09</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Navigation-source,Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840315.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004840283.09</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840324.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004840283.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarAutoSize</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840266.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1004840222.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>Adm2Navigation,txtaction,AstraHelp,AstraWindow,AstraAbout,AstraMenuExit,DynamicMenu</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840327.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004840283.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>browsetableio,browsesearch,browsefunction</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840336.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004837652.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004840283.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarParentMenu</attribute_label>
<character_value>Help</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004840199.09</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>1004837652.09</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WindowName</attribute_label>
<character_value>Context Help Control</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004837652.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>