/************************************************
Copyright (c) 2019 by Progress Software Corporation. All rights reserved.
*************************************************/ 
/*------------------------------------------------------------------------
    File        : JsonPropertyNameEnum
    Purpose     : Name of JSON properties 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : 2019-11-22
    Notes       : 
  ----------------------------------------------------------------------*/
enum OpenEdge.BusinessLogic.IO.JsonPropertyNameEnum :  
    define enum commitScope
                customParameter
                customRequest
                customResponse
                entries
                exact
                fieldName
                filter
                join
                name
                namedQuery
                nextPagingCtx
                numResults
                object
                operator
                order
                pagingCtx
                params
                prevPagingCtx
                query
                resultCounts
                tableName
                request
                requests
                response
                responses
                skip
                sort
                top
                typeName
                value
                .
end enum.
