<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1"><dataset_header DisableRI="yes" DatasetObj="1004928896.09" DateFormat="mdy" FullHeader="no" SCMManaged="yes" YearOffset="1950" DatasetCode="RYCSO" NumericFormat="AMERICAN" NumericDecimal="." OriginatingSite="91" NumericSeparator=","/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" version_date="02/09/2004" version_time="47996" version_user="admin" deletion_flag="no" entity_mnemonic="RYCSO" key_field_value="1004870754.09" record_version_obj="3000050002.09" version_number_seq="5.09" secondary_key_value="gscsqobjcw#CHR(1)#0" import_version_number_seq="5.09"><smartobject_obj>1004870754.09</smartobject_obj>
<object_filename>gscsqobjcw</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>1003498202</object_type_obj>
<product_module_obj>1004874679.09</product_module_obj>
<layout_obj>1003501078</layout_obj>
<object_description>Sequence Object Controller</object_description>
<object_path>af/cod2</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>yes</runnable_from_menu>
<container_object>yes</container_object>
<disabled>no</disabled>
<run_persistent>yes</run_persistent>
<run_when>ANY</run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>0</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>1004870754.09</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004871372.09</object_instance_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>bottom</layout_position>
<instance_name>BrowseToolbar</instance_name>
<instance_description>BrowseToolbar</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004871293.09</object_instance_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1004870736.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>centre2</layout_position>
<instance_name>gscsqfullb</instance_name>
<instance_description>gscsqfullb</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004871291.09</object_instance_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1004870727.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>gscsqfullo.w</instance_name>
<instance_description>gscsqfullo.w</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1004871311.09</object_instance_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>top</layout_position>
<instance_name>ObjcTop</instance_name>
<instance_description>ObjcTop</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004871439.09</smartlink_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartlink_type_obj>1003578295</smartlink_type_obj>
<link_name>PrimarySdo</link_name>
<source_object_instance_obj>0</source_object_instance_obj>
<target_object_instance_obj>1004871291.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004871447.09</smartlink_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartlink_type_obj>1003183649</smartlink_type_obj>
<link_name>Data</link_name>
<source_object_instance_obj>1004871291.09</source_object_instance_obj>
<target_object_instance_obj>1004871293.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004871449.09</smartlink_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartlink_type_obj>1003183650</smartlink_type_obj>
<link_name>Update</link_name>
<source_object_instance_obj>1004871293.09</source_object_instance_obj>
<target_object_instance_obj>1004871291.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004871441.09</smartlink_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartlink_type_obj>463.5498</smartlink_type_obj>
<link_name>ContainerToolbar</link_name>
<source_object_instance_obj>1004871311.09</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004871451.09</smartlink_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1004871311.09</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004871443.09</smartlink_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1004871372.09</source_object_instance_obj>
<target_object_instance_obj>1004871291.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1004871445.09</smartlink_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartlink_type_obj>1003543798</smartlink_type_obj>
<link_name>Toolbar</link_name>
<source_object_instance_obj>1004871372.09</source_object_instance_obj>
<target_object_instance_obj>1004871293.09</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2009.66</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1004871311.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DeactivateTargetOnHide</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2469.66</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004871372.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DeactivateTargetOnHide</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004871343.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1004871311.09</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Navigation-source,Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004871404.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004871372.09</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004871413.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004871372.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarAutoSize</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004871355.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1004871311.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>Adm2Navigation,txtaction,AstraHelp,AstraWindow,AstraAbout,AstraMenuExit,DynamicMenu</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004871416.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004871372.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>browsetableio,browsesearch,browsefunction</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004871425.09</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1004870754.09</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1004871372.09</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarParentMenu</attribute_label>
<character_value>Sequence</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1004871289.09</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>1004870754.09</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WindowName</attribute_label>
<character_value>Sequence Control</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1004870754.09</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>