<?xml version="1.0" encoding="utf-8" ?>
<dataset Transactions="1"><dataset_header DisableRI="yes" DatasetObj="1004928896.09" DateFormat="mdy" FullHeader="no" SCMManaged="yes" YearOffset="1950" DatasetCode="RYCSO" NumericFormat="AMERICAN" NumericDecimal="." OriginatingSite="91" NumericSeparator=","/>
<dataset_records><dataset_transaction TransactionNo="1" TransactionType="DATA"><contained_record DB="icfdb" Table="ryc_smartobject" version_date="02/09/2004" version_time="47998" version_user="admin" deletion_flag="no" entity_mnemonic="RYCSO" key_field_value="1005117525.101" record_version_obj="3000050038.09" version_number_seq="5.09" secondary_key_value="gsmmmimgcw#CHR(1)#0" import_version_number_seq="5.09"><smartobject_obj>1005117525.101</smartobject_obj>
<object_filename>gsmmmimgcw</object_filename>
<customization_result_obj>0</customization_result_obj>
<object_type_obj>1003498202</object_type_obj>
<product_module_obj>1004874679.09</product_module_obj>
<layout_obj>1003501078</layout_obj>
<object_description>Multi Media Image Control</object_description>
<object_path>af/cod2</object_path>
<object_extension></object_extension>
<static_object>no</static_object>
<generic_object>no</generic_object>
<template_smartobject>no</template_smartobject>
<system_owned>no</system_owned>
<deployment_type></deployment_type>
<design_only>no</design_only>
<runnable_from_menu>yes</runnable_from_menu>
<container_object>yes</container_object>
<disabled>no</disabled>
<run_persistent>yes</run_persistent>
<run_when>ANY</run_when>
<shutdown_message_text></shutdown_message_text>
<required_db_list></required_db_list>
<sdo_smartobject_obj>0</sdo_smartobject_obj>
<extends_smartobject_obj>0</extends_smartobject_obj>
<security_smartobject_obj>1005117525.101</security_smartobject_obj>
<object_is_runnable>yes</object_is_runnable>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1005117572.101</object_instance_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>bottom</layout_position>
<instance_name>BrowseToolbar</instance_name>
<instance_description>BrowseToolbar</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1005117544.101</object_instance_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1005117510.101</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>centre2</layout_position>
<instance_name>gsmmmfullb</instance_name>
<instance_description>gsmmmfullb</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1005117532.101</object_instance_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1005117410.101</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>Centre</layout_position>
<instance_name>gsmmmfullo.w</instance_name>
<instance_description>gsmmmfullo.w</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_object_instance"><object_instance_obj>1005117552.101</object_instance_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<system_owned>no</system_owned>
<layout_position>top</layout_position>
<instance_name>ObjcTop</instance_name>
<instance_description>ObjcTop</instance_description>
<page_obj>0</page_obj>
<object_sequence>0</object_sequence>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1005117592.101</smartlink_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartlink_type_obj>1003578295</smartlink_type_obj>
<link_name>PrimarySdo</link_name>
<source_object_instance_obj>0</source_object_instance_obj>
<target_object_instance_obj>1005117532.101</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1005117596.101</smartlink_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartlink_type_obj>1003183649</smartlink_type_obj>
<link_name>Data</link_name>
<source_object_instance_obj>1005117532.101</source_object_instance_obj>
<target_object_instance_obj>1005117544.101</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1005117597.101</smartlink_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartlink_type_obj>1003183650</smartlink_type_obj>
<link_name>Update</link_name>
<source_object_instance_obj>1005117544.101</source_object_instance_obj>
<target_object_instance_obj>1005117532.101</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1005117593.101</smartlink_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartlink_type_obj>463.5498</smartlink_type_obj>
<link_name>ContainerToolbar</link_name>
<source_object_instance_obj>1005117552.101</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1005117598.101</smartlink_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1005117552.101</source_object_instance_obj>
<target_object_instance_obj>0</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1005117594.101</smartlink_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartlink_type_obj>1003183651</smartlink_type_obj>
<link_name>Navigation</link_name>
<source_object_instance_obj>1005117572.101</source_object_instance_obj>
<target_object_instance_obj>1005117532.101</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_smartlink"><smartlink_obj>1005117595.101</smartlink_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartlink_type_obj>1003543798</smartlink_type_obj>
<link_name>Toolbar</link_name>
<source_object_instance_obj>1005117572.101</source_object_instance_obj>
<target_object_instance_obj>1005117544.101</target_object_instance_obj>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2081.66</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1005117552.101</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DeactivateTargetOnHide</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>2541.66</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1005117572.101</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>DeactivateTargetOnHide</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1005117563.101</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1005117552.101</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Navigation-source,Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1005117583.101</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1005117572.101</object_instance_obj>
<constant_value>yes</constant_value>
<attribute_label>SupportedLinks</attribute_label>
<character_value>Toolbar-source</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1005117586.101</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1005117572.101</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarAutoSize</attribute_label>
<character_value></character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1005117567.101</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708413.09</smartobject_obj>
<object_instance_obj>1005117552.101</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>Adm2Navigation,txtaction,AstraHelp,AstraWindow,AstraAbout,AstraMenuExit,DynamicMenu</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1005117587.101</attribute_value_obj>
<object_type_obj>1003498168</object_type_obj>
<container_smartobject_obj>1005117525.101</container_smartobject_obj>
<smartobject_obj>1000708739.09</smartobject_obj>
<object_instance_obj>1005117572.101</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>ToolbarBands</attribute_label>
<character_value>browsetableio,browsesearch,browsefunction</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
<contained_record DB="icfdb" Table="ryc_attribute_value"><attribute_value_obj>1005117531.101</attribute_value_obj>
<object_type_obj>1003498202</object_type_obj>
<container_smartobject_obj>0</container_smartobject_obj>
<smartobject_obj>1005117525.101</smartobject_obj>
<object_instance_obj>0</object_instance_obj>
<constant_value>no</constant_value>
<attribute_label>WindowName</attribute_label>
<character_value>Multi Media Image Control</character_value>
<integer_value>0</integer_value>
<date_value>?</date_value>
<decimal_value>0</decimal_value>
<logical_value>no</logical_value>
<primary_smartobject_obj>1005117525.101</primary_smartobject_obj>
<render_type_obj>0</render_type_obj>
<applies_at_runtime>yes</applies_at_runtime>
</contained_record>
</contained_record>
</dataset_transaction>
</dataset_records>
</dataset>