/*************************************************************/
/* Copyright (c) 1984-2005 by Progress Software Corporation  */
/*                                                           */
/* All rights reserved.  No part of this program or document */
/* may be  reproduced in  any form  or by  any means without */
/* permission in writing from PROGRESS Software Corporation. */
/*************************************************************/
DEFINE INPUT PARAMETER piDim AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER pcExtent AS CHAR EXTENT. 

RUN VALUE('getDim' + STRING(piDim)) IN TARGET-PROCEDURE (OUTPUT pcExtent) NO-ERROR. 
IF ERROR-STATUS:ERROR THEN
   MESSAGE
      "Procedure" program-name(1) "cannot create" piDim "extents."
      "Maximum number is" 
      STRING(NUM-ENTRIES(TARGET-PROCEDURE:INTERNAL-ENTRIES)) + "."
     VIEW-AS ALERT-BOX WARNING.

PROCEDURE getDim1 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 1. END.
PROCEDURE getDim2 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 2. END.
PROCEDURE getDim3 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 3. END.
PROCEDURE getDim4 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 4. END.
PROCEDURE getDim5 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 5. END.
PROCEDURE getDim6 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 6. END.
PROCEDURE getDim7 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 7. END.
PROCEDURE getDim8 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 8. END.
PROCEDURE getDim9 PRIVATE:  DEF OUTPUT param c AS CHAR EXTENT 9. END.
PROCEDURE getDim10 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 10. END.
PROCEDURE getDim11 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 11. END.
PROCEDURE getDim12 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 12. END.
PROCEDURE getDim13 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 13. END.
PROCEDURE getDim14 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 14. END.
PROCEDURE getDim15 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 15. END.
PROCEDURE getDim16 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 16. END.
PROCEDURE getDim17 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 17. END.
PROCEDURE getDim18 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 18. END.
PROCEDURE getDim19 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 19. END.
PROCEDURE getDim20 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 20. END.
PROCEDURE getDim21 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 21. END.
PROCEDURE getDim22 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 22. END.
PROCEDURE getDim23 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 23. END.
PROCEDURE getDim24 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 24. END.
PROCEDURE getDim25 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 25. END.
PROCEDURE getDim26 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 26. END.
PROCEDURE getDim27 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 27. END.
PROCEDURE getDim28 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 28. END.
PROCEDURE getDim29 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 29. END.
PROCEDURE getDim30 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 30. END.
PROCEDURE getDim31 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 31. END.
PROCEDURE getDim32 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 32. END.
PROCEDURE getDim33 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 33. END.
PROCEDURE getDim34 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 34. END.
PROCEDURE getDim35 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 35. END.
PROCEDURE getDim36 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 36. END.
PROCEDURE getDim37 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 37. END.
PROCEDURE getDim38 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 38. END.
PROCEDURE getDim39 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 39. END.
PROCEDURE getDim40 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 40. END.
PROCEDURE getDim41 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 41. END.
PROCEDURE getDim42 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 42. END.
PROCEDURE getDim43 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 43. END.
PROCEDURE getDim44 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 44. END.
PROCEDURE getDim45 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 45. END.
PROCEDURE getDim46 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 46. END.
PROCEDURE getDim47 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 47. END.
PROCEDURE getDim48 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 48. END.
PROCEDURE getDim49 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 49. END.
PROCEDURE getDim50 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 50. END.
PROCEDURE getDim51 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 51. END.
PROCEDURE getDim52 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 52. END.
PROCEDURE getDim53 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 53. END.
PROCEDURE getDim54 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 54. END.
PROCEDURE getDim55 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 55. END.
PROCEDURE getDim56 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 56. END.
PROCEDURE getDim57 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 57. END.
PROCEDURE getDim58 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 58. END.
PROCEDURE getDim59 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 59. END.
PROCEDURE getDim60 PRIVATE: DEF OUTPUT param c AS CHAR EXTENT 60. END.
 
