/* Generated by ICF ERwin Template */
/* %Parent %VerbPhrase %Child ON PARENT DELETE RESTRICT */
%If(%!=(%Child, %Parent)) {
IF CAN-FIND(FIRST %Child WHERE
    %JoinFKPK(%Child,%Parent," = "," and")) THEN
    DO:
      /* Cannot delete parent because child exists! */
      ASSIGN lv-error = YES lv-errgrp = "AF ":U lv-errnum = 101 lv-include = "%Parent|%Child":U.
      RUN error-message (lv-errgrp, lv-errnum, lv-include).
    END.
}
%If(%==(%Child, %Parent)) {
IF CAN-FIND(FIRST lb_table WHERE
    %JoinFKPK(lb_table,%Parent," = "," and")) THEN
    DO:
      /* Cannot delete parent because child exists! */
      ASSIGN lv-error = YES lv-errgrp = "AF ":U lv-errnum = 101 lv-include = "%Parent|%Child":U.
      RUN error-message (lv-errgrp, lv-errnum, lv-include).
    END.
}
